version: "3.9"
services:
  auth:
    build: .
    image: maven:3.8.4-openjdk-17
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/app/target:/usr/src/app/target
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_URL=db:3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: "mvn spring-boot:run"
    working_dir: /app

  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - bd_authentification:/var/lib/mysql

  #Oauth

  mysql:
    image: mysql:5.7
    volumes:
      - bd_keycloak:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    image: jboss/keycloak
    environment:
      MYSQL_USER: keycloak
      MYSQL_DATABASE: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - "8081:8080"
    volumes:
      - keycloack:/tmp
volumes:
  bd_keycloak:
    driver: local
  bd_authentification:
    driver: local
  keycloack:
    driver: local